name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Node.js et npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'

 
    - name: Update / upgrade 
      run: sudo apt update


    - name: Installer les dépendances
      run: npm install

    - name: Install Jest
      run: npm install --save-dev jest --force
  
    - name: connect to dockerhub
      run: docker login -u king12quentin --password="$DOCKERPASSWORD"

    - name: upload to dockerhub
      run: docker tag meteoapp "king12quentin/meteoapp" && docker push "king12quentin/meteoapp"

