name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Node.js et npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'

 
    - name: Update / upgrade 
      run: sudo apt update


    - name: Installer les dépendances
      run: npm install

    - name: Install Jest
      run: npm install --save-dev jest --force
  
    - name: Docker
      run: docker build -t meteoappfinal .

    - name: Install Jest
      run: docker run -p 8282:8282 meteoappfinal

    - name: connect to dockerhub
      run: sudo docker login -u king12quentin -p ${{ secrets.SECRET }}

    - name: upload to dockerhub
      run: docker tag meteoappfinal "king12quentin/meteoappfinal" && docker push "king12quentin/meteoappfinal"

