name: CI

on:
  push:
    branches:
      - featureNils

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Node.js et npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Installer les dépendances
      run: npm install

    - run:
      name: Install Jest
      command: npm install --save-dev jest --force

    - name: Exécution des tests
      run: npm test

    - name: Construction et publication Docker
      if: success()
      run: |
        # Commandes pour dockeriser l'application
        # Assurez-vous d'ajouter les tags en fonction du type de build

        docker build -t mon_application:latest .
        docker tag mon_application:latest mon_application:v1 # Exemple de tagging
        # Ajoutez d'autres étapes de taggage si nécessaire

        docker push mon_application:latest
        docker push mon_application:v1
        # Assurez-vous de pusher les images Docker dans le registre approprié
